use crate::proto::tools::{RtkRequest, TdsRequest, TextRequest, BudgetRequest, CogRequest, ToolResult};
use tiktoken_rs::cl100k_base;
use similar::{TextDiff, ChangeTag};

/// Count tokens in text using cl100k_base (gpt-4 compatible, best proxy for Claude).
pub fn count_tokens(text: &str) -> usize {
    let bpe = cl100k_base().unwrap();
    bpe.encode_with_special_tokens(text).len()
}

/// RTK: Reduced Token Kernel.
/// Greedily selects chunks that fit within budget_tokens, ranked by relevance_score / token_count.
pub fn rtk(req: RtkRequest) -> ToolResult {
    let budget = req.budget_tokens as usize;
    if budget == 0 {
        return err_result("budget_tokens must be > 0");
    }
    let bpe = match cl100k_base() {
        Ok(b) => b,
        Err(e) => return err_result(&format!("tiktoken error: {e}")),
    };

    let mut scored: Vec<(usize, f32, &str, &str)> = req
        .chunks
        .iter()
        .map(|c| {
            let tokens = bpe.encode_with_special_tokens(&c.text).len().max(1);
            let score = if c.relevance_score > 0.0 {
                c.relevance_score / tokens as f32
            } else {
                1.0 / tokens as f32
            };
            (tokens, score, c.text.as_str(), c.id.as_str())
        })
        .collect();

    // Sort by density descending
    scored.sort_by(|a, b| b.1.partial_cmp(&a.1).unwrap_or(std::cmp::Ordering::Equal));

    let mut used = 0usize;
    let mut selected: Vec<serde_json::Value> = Vec::new();
    for (tokens, score, text, id) in &scored {
        if used + tokens > budget {
            continue;
        }
        used += tokens;
        selected.push(serde_json::json!({
            "id": id,
            "tokens": tokens,
            "score": score,
            "text": text,
        }));
    }

    ok_result(serde_json::json!({
        "selected": selected,
        "tokens_used": used,
        "budget": budget,
        "dropped": req.chunks.len() - selected.len(),
    }))
}

/// TDS: Token Diff Slicer.
/// Extracts unified diff hunks ± context_lines, token-counts each hunk.
pub fn tds(req: TdsRequest) -> ToolResult {
    let context = if req.context_lines > 0 { req.context_lines as usize } else { 3 };
    let diff = TextDiff::from_lines("", &req.diff);
    let bpe = match cl100k_base() {
        Ok(b) => b,
        Err(e) => return err_result(&format!("tiktoken error: {e}")),
    };

    let mut hunks: Vec<serde_json::Value> = Vec::new();
    let mut total_tokens = 0usize;

    for (idx, group) in diff.grouped_ops(context).iter().enumerate() {
        let mut lines: Vec<String> = Vec::new();
        for op in group {
            for change in diff.iter_changes(op) {
                let prefix = match change.tag() {
                    ChangeTag::Delete => "-",
                    ChangeTag::Insert => "+",
                    ChangeTag::Equal => " ",
                };
                lines.push(format!("{}{}", prefix, change.value()));
            }
        }
        let hunk_text = lines.join("");
        let tokens = bpe.encode_with_special_tokens(&hunk_text).len();
        total_tokens += tokens;

        if req.budget_tokens > 0 && total_tokens > req.budget_tokens as usize {
            break;
        }
        hunks.push(serde_json::json!({
            "index": idx,
            "tokens": tokens,
            "text": hunk_text,
        }));
    }

    ok_result(serde_json::json!({
        "hunks": hunks,
        "total_tokens": total_tokens,
    }))
}

/// Noise-Token Filter.
/// Strips boilerplate: shebangs, auto-gen headers, repeated blank lines, trailing whitespace.
pub fn noise_filter(req: TextRequest) -> ToolResult {
    let text = &req.content;
    let mut lines: Vec<&str> = text.lines().collect();

    // Remove shebang line
    if lines.first().map(|l| l.starts_with("#!")).unwrap_or(false) {
        lines.remove(0);
    }

    // Remove auto-generated header comments (first block of lines matching common patterns)
    let autogen_re = regex::Regex::new(
        r"(?i)(auto.?gen|generated by|do not edit|this file is generated|code generated)"
    ).unwrap();
    let mut first_real = 0;
    for (i, line) in lines.iter().enumerate() {
        if autogen_re.is_match(line) || line.trim().is_empty() || line.trim_start().starts_with("//") || line.trim_start().starts_with('#') || line.trim_start().starts_with('*') || line.trim_start().starts_with("/*") {
            first_real = i + 1;
        } else {
            break;
        }
    }
    // Only strip if it looks like a pure header (< 20 lines)
    if first_real < 20 && first_real > 0 && autogen_re.is_match(&lines[..first_real].join("\n")) {
        lines = lines[first_real..].to_vec();
    }

    // Collapse multiple blank lines to one
    let mut result_lines: Vec<&str> = Vec::new();
    let mut prev_blank = false;
    for line in &lines {
        let blank = line.trim().is_empty();
        if blank && prev_blank {
            continue;
        }
        result_lines.push(line);
        prev_blank = blank;
    }

    let filtered = result_lines.join("\n");
    let bpe = cl100k_base().unwrap();
    let orig_tokens = bpe.encode_with_special_tokens(text).len();
    let new_tokens = bpe.encode_with_special_tokens(&filtered).len();

    ok_result(serde_json::json!({
        "text": filtered,
        "original_tokens": orig_tokens,
        "filtered_tokens": new_tokens,
        "saved_tokens": orig_tokens.saturating_sub(new_tokens),
    }))
}

/// Context-Window Budgeter.
/// Fractional knapsack over priority × token_cost to fill budget.
pub fn budget(req: BudgetRequest) -> ToolResult {
    let capacity = req.budget_tokens as usize;
    let bpe = match cl100k_base() {
        Ok(b) => b,
        Err(e) => return err_result(&format!("tiktoken error: {e}")),
    };

    let mut items: Vec<(usize, f32, &str, &str)> = req
        .items
        .iter()
        .map(|it| {
            let tokens = bpe.encode_with_special_tokens(&it.text).len().max(1);
            let density = it.priority / tokens as f32;
            (tokens, density, it.text.as_str(), it.id.as_str())
        })
        .collect();

    // Sort by priority density descending
    items.sort_by(|a, b| b.1.partial_cmp(&a.1).unwrap_or(std::cmp::Ordering::Equal));

    let mut used = 0usize;
    let mut packed: Vec<serde_json::Value> = Vec::new();
    for (tokens, density, text, id) in &items {
        if used + tokens <= capacity {
            used += tokens;
            packed.push(serde_json::json!({
                "id": id,
                "tokens": tokens,
                "priority_density": density,
                "text": text,
            }));
        }
    }

    ok_result(serde_json::json!({
        "packed": packed,
        "tokens_used": used,
        "budget": capacity,
        "dropped": req.items.len() - packed.len(),
    }))
}

/// COG: Claude Output Governor.
/// Truncates text to max_tokens at a sentence/paragraph/line boundary.
pub fn cog(req: CogRequest) -> ToolResult {
    let max = req.max_tokens as usize;
    if max == 0 {
        return ok_result(serde_json::json!({ "text": "", "truncated": false, "tokens": 0 }));
    }
    let bpe = match cl100k_base() {
        Ok(b) => b,
        Err(e) => return err_result(&format!("tiktoken error: {e}")),
    };

    let tokens = bpe.encode_with_special_tokens(&req.text).len();
    if tokens <= max {
        return ok_result(serde_json::json!({
            "text": req.text,
            "truncated": false,
            "tokens": tokens,
        }));
    }

    let boundary = if req.boundary.is_empty() { "sentence" } else { req.boundary.as_str() };

    // Split into segments by boundary type
    let segments: Vec<&str> = match boundary {
        "paragraph" => req.text.split("\n\n").collect(),
        "line" => req.text.lines().collect(),
        _ => {
            // sentence: split on '. ', '! ', '? '
            let re = regex::Regex::new(r"(?<=[.!?])\s+").unwrap();
            re.split(&req.text).collect()
        }
    };

    let mut result = String::new();
    let mut used = 0usize;
    let sep = match boundary {
        "paragraph" => "\n\n",
        "line" => "\n",
        _ => " ",
    };

    for seg in &segments {
        let seg_tokens = bpe.encode_with_special_tokens(seg).len();
        if used + seg_tokens > max {
            break;
        }
        if !result.is_empty() {
            result.push_str(sep);
        }
        result.push_str(seg);
        used += seg_tokens;
    }

    ok_result(serde_json::json!({
        "text": result,
        "truncated": true,
        "tokens": used,
        "original_tokens": tokens,
    }))
}

// ---------------------------------------------------------------------------
// helpers
// ---------------------------------------------------------------------------

pub fn ok_result(data: serde_json::Value) -> ToolResult {
    ToolResult {
        ok: true,
        error: String::new(),
        data: Some(json_to_struct(data)),
        text: String::new(),
    }
}

pub fn err_result(msg: &str) -> ToolResult {
    ToolResult {
        ok: false,
        error: msg.to_string(),
        data: None,
        text: String::new(),
    }
}

pub fn ok_text(text: String) -> ToolResult {
    ToolResult {
        ok: true,
        error: String::new(),
        data: None,
        text,
    }
}

pub fn json_to_struct(v: serde_json::Value) -> prost_types::Struct {
    use prost_types::value::Kind;
    use prost_types::{Value as PValue, ListValue};

    fn convert(v: serde_json::Value) -> PValue {
        PValue {
            kind: Some(match v {
                serde_json::Value::Null => Kind::NullValue(0),
                serde_json::Value::Bool(b) => Kind::BoolValue(b),
                serde_json::Value::Number(n) => Kind::NumberValue(n.as_f64().unwrap_or(0.0)),
                serde_json::Value::String(s) => Kind::StringValue(s),
                serde_json::Value::Array(arr) => Kind::ListValue(ListValue {
                    values: arr.into_iter().map(convert).collect(),
                }),
                serde_json::Value::Object(map) => Kind::StructValue(prost_types::Struct {
                    fields: map.into_iter().map(|(k, v)| (k, convert(v))).collect(),
                }),
            }),
        }
    }

    if let serde_json::Value::Object(map) = v {
        prost_types::Struct {
            fields: map.into_iter().map(|(k, v)| (k, convert(v))).collect(),
        }
    } else {
        prost_types::Struct {
            fields: [("value".to_string(), convert(v))].into_iter().collect(),
        }
    }
}
